/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static Ventanas.Sala1.arch;
import static Ventanas.Sala2.arch2;
import static Ventanas.VUsuario.arch3;
import javax.swing.JOptionPane;
import static Ventanas.Metodos.pelin;

/**
 *
 * @author usuario
 */
public class Administrador extends javax.swing.JFrame {

   static File arch5 = new File("Descripcion.txt");
    Metodos m = new Metodos();

    public Administrador() throws IOException {
        initComponents();
        Nodo ptr= m.agregarNodosDescripcion(arch5);
        m.ComboboxPeliculas(ptr, peliculas);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sala = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Peliculas = new javax.swing.JPanel();
        Bsala1 = new javax.swing.JButton();
        Bsala2 = new javax.swing.JButton();
        Boletas = new javax.swing.JPanel();
        Sala1 = new javax.swing.JRadioButton();
        Sala2 = new javax.swing.JRadioButton();
        pelicula = new javax.swing.JComboBox<>();
        horario = new javax.swing.JComboBox<>();
        cantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Continuar = new javax.swing.JButton();
        Reservas = new javax.swing.JPanel();
        Boletas1 = new javax.swing.JPanel();
        consultar = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cant = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        Salas = new javax.swing.JPanel();
        peliculas = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        VolverVUsuario = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bsala1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Bsala1.setText("Sala1");
        Bsala1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsala1ActionPerformed(evt);
            }
        });

        Bsala2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Bsala2.setText("Sala2");
        Bsala2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsala2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PeliculasLayout = new javax.swing.GroupLayout(Peliculas);
        Peliculas.setLayout(PeliculasLayout);
        PeliculasLayout.setHorizontalGroup(
            PeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeliculasLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(Bsala1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(Bsala2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        PeliculasLayout.setVerticalGroup(
            PeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeliculasLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(PeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bsala1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bsala2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Peliculas", Peliculas);

        Sala.add(Sala1);
        Sala1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sala1.setText("Sala1");
        Sala1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sala1ActionPerformed(evt);
            }
        });

        Sala.add(Sala2);
        Sala2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Sala2.setText("Sala2");
        Sala2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sala2ActionPerformed(evt);
            }
        });

        pelicula.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pelicula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja película" }));
        pelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculaActionPerformed(evt);
            }
        });

        horario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        horario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja horario" }));
        horario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horarioActionPerformed(evt);
            }
        });

        cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadActionPerformed(evt);
            }
        });
        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Digite cantidad de boletas");

        Continuar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Continuar.setText("Continuar");
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BoletasLayout = new javax.swing.GroupLayout(Boletas);
        Boletas.setLayout(BoletasLayout);
        BoletasLayout.setHorizontalGroup(
            BoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoletasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(BoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoletasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Continuar)
                        .addGap(27, 27, 27))
                    .addGroup(BoletasLayout.createSequentialGroup()
                        .addGroup(BoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 300, Short.MAX_VALUE))))
            .addGroup(BoletasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(BoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoletasLayout.createSequentialGroup()
                        .addGroup(BoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Sala2)
                            .addComponent(Sala1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BoletasLayout.createSequentialGroup()
                        .addGroup(BoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        BoletasLayout.setVerticalGroup(
            BoletasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoletasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Sala1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sala2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoletasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Continuar)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Boletas", Boletas);

        consultar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Digite el documento del ususario");

        nom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("comprar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Película");

        jLabel5.setText("Horario");

        jLabel7.setText("Cantidad de Boletas ");

        jLabel6.setText("ID");

        javax.swing.GroupLayout Boletas1Layout = new javax.swing.GroupLayout(Boletas1);
        Boletas1.setLayout(Boletas1Layout);
        Boletas1Layout.setHorizontalGroup(
            Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Boletas1Layout.createSequentialGroup()
                .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Boletas1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(Boletas1Layout.createSequentialGroup()
                        .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Boletas1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(consultar))
                            .addGroup(Boletas1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2))
                            .addGroup(Boletas1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Boletas1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Boletas1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6))
                                        .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Boletas1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(Boletas1Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(Boletas1Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 63, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Boletas1Layout.setVerticalGroup(
            Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Boletas1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultar))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(Boletas1Layout.createSequentialGroup()
                        .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Boletas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cant)
                            .addComponent(jLabel7))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ReservasLayout = new javax.swing.GroupLayout(Reservas);
        Reservas.setLayout(ReservasLayout);
        ReservasLayout.setHorizontalGroup(
            ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boletas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ReservasLayout.setVerticalGroup(
            ReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Boletas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Reservas", Reservas);

        Salas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        peliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una pelicula" }));
        peliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peliculasMouseClicked(evt);
            }
        });
        peliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculasActionPerformed(evt);
            }
        });
        Salas.add(peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Salas.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel8.setText("DESCRIPCIÓN");
        Salas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel9.setText("¿Qué película deseas buscar?");
        Salas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        nombre.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        Salas.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 370, 30));
        Salas.add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 260, 90));

        jTabbedPane1.addTab("consulta", Salas);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 480, 300));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, -1));

        VolverVUsuario.setBackground(new java.awt.Color(0, 0, 0));
        VolverVUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        VolverVUsuario.setForeground(new java.awt.Color(255, 255, 255));
        VolverVUsuario.setText("Volver");
        VolverVUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverVUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(VolverVUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tu-FILM");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 160, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/4257.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        if (!id.getText().equals("")) {
            Nodo ptr = null;
            try {
                ptr = m.agregarnodosReserva(arch3);
            } catch (IOException ex) {
                Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
            Nodo q = m.consultarReserva(ptr, id.getText());
            if (q != null) {
                nom.setText(q.pelicula);
                hora.setText(q.horaI+" - "+q.HoraF);
                cant.setText(q.cantidad);
                ID.setText(q.id);
            } else {
                nom.setText("Esta persona no ha hecho reservas");
                hora.setText("");
                cant.setText("");
                ID.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite un documento");
        }
    }//GEN-LAST:event_consultarActionPerformed

    private void Sala1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sala1ActionPerformed
        try {
            m.agregarcombobox(arch, pelicula);
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Sala1ActionPerformed

    private void horarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horarioActionPerformed

    }//GEN-LAST:event_horarioActionPerformed

    private void peliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculaActionPerformed
        String x = (String) pelicula.getSelectedItem();
        try {
            if (Sala1.isSelected()) {
                m.agregarhora(arch, horario, x);
            } else {
                if (Sala2.isSelected()) {
                    m.agregarhora(arch2, horario, x);
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_peliculaActionPerformed

    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed
        if ((Sala1.isSelected() || Sala2.isSelected()) && !pelicula.getSelectedItem().equals("Escoja pelicula") && !horario.getSelectedItem().equals("Escoja horario") && !cantidad.getText().equals("")) {
            Nodo ptr = null;
            try {
                if (Sala1.isSelected()) {
                    ptr = m.agregarnodos(arch);
                    Nodo q = m.comprar(ptr, horario.getSelectedItem().toString(), pelicula.getSelectedItem().toString(), cantidad.getText());
                    if (q != null) {
                        m.guardar(arch, q);
                        Table t = new Table(m.creararchivo("S1" + pelicula.getSelectedItem().toString(), horario.getSelectedItem().toString()));
                        t.setVisible(true);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(null, "La cantidad de boletas que necesita, no esta disponible");
                    }
                } else {
                    if (Sala2.isSelected()) {
                        ptr = m.agregarnodos(arch2);
                        Nodo q = m.comprar(ptr, horario.getSelectedItem().toString(), pelicula.getSelectedItem().toString(), cantidad.getText());
                        if (q != null) {
                            m.guardar(arch2, q);
                            Table t = new Table(m.creararchivo("S2" + pelicula.getSelectedItem().toString(), horario.getSelectedItem().toString()));
                            t.setVisible(true);
                            this.setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(null, "La cantidad de boletas que necesita, no esta disponible");
                        }
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione todos los campos");
        }

    }//GEN-LAST:event_ContinuarActionPerformed

    private void Bsala1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsala1ActionPerformed
        Sala1 s1 = null;
        this.setVisible(false);
        try {
            s1 = new Sala1();
            s1.setVisible(true);
            // s1.setBounds(12, 12, 500, 600);
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_Bsala1ActionPerformed

    private void Bsala2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsala2ActionPerformed
        try {
            Sala2 s2 = new Sala2();
            this.setVisible(false);
            s2.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Bsala2ActionPerformed

    private void Sala2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sala2ActionPerformed
        try {
            m.agregarcombobox(arch2, pelicula);
        } catch (IOException ex) {
            Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Sala2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (!id.getText().equals("")) {
            try {
                Nodo ptr = m.agregarnodosReserva(arch3);
                Nodo q = m.consultarReserva(ptr, id.getText());
                if (q != null) {
                    nom.setText(q.id + " \n " + q.horaI + " \n " + q.HoraF + " \n " + q.cantidad + " \n " + q.pelicula);
                    File pelicula = new File(q.Sala + q.pelicula + q.horaI.substring(0, q.horaI.length() - 3) + ".txt");
                   // System.out.println("file " + pelicula.getName());
                    if (pelicula.exists()) {
                        m.EliminarReserva(arch3, q, ptr);
                        TableCR t = new TableCR(pelicula);
                        t.setVisible(true);
                    } else{
                        JOptionPane.showMessageDialog(null, "esta pelicula fue retirada de cartelera");
                        m.EliminarReserva(arch3, q, ptr);
                    }
                } else {
                    nom.setText("Esta persona no ha hecho reservas");
                }
            } catch (IOException ex) {
                Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Digite una id");
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void VolverVUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverVUsuarioActionPerformed
        new Interface().setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_VolverVUsuarioActionPerformed

    private void peliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peliculasMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_peliculasMouseClicked

    private void peliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_peliculasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        try {

            if (!peliculas.getSelectedItem().equals("Escoja una pelicula")){
                String Peli=  peliculas.getSelectedItem().toString();
                Nodo ptr;
                ptr = m.agregarNodosDescripcion(arch5);
                Nodo q=m.buscarDescripcion(Peli, ptr);
                if (q!=null){
                    nombre.setText(q.pelicula);
                    desc.setText(q.descripcion);
                }
            } else{
                JOptionPane.showMessageDialog(null, "Elija una pelicula");
                nombre.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(Consultas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadActionPerformed

    private void cantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadKeyPressed

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
    char c= evt.getKeyChar();
    if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_cantidadKeyTyped

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
     char c= evt.getKeyChar();
    if(c<'0' || c>'9')evt.consume();
    }//GEN-LAST:event_idKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Administrador().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Administrador.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Boletas;
    private javax.swing.JPanel Boletas1;
    private javax.swing.JButton Bsala1;
    private javax.swing.JButton Bsala2;
    private javax.swing.JButton Continuar;
    private javax.swing.JLabel ID;
    private javax.swing.JPanel Peliculas;
    private javax.swing.JPanel Reservas;
    private javax.swing.ButtonGroup Sala;
    private javax.swing.JRadioButton Sala1;
    private javax.swing.JRadioButton Sala2;
    private javax.swing.JPanel Salas;
    private javax.swing.JButton VolverVUsuario;
    private javax.swing.JLabel cant;
    private javax.swing.JTextField cantidad;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel hora;
    private javax.swing.JComboBox<String> horario;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel nombre;
    private javax.swing.JComboBox<String> pelicula;
    private javax.swing.JComboBox<String> peliculas;
    // End of variables declaration//GEN-END:variables
}
