/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Ventanas.Sala1.arch;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 8.1
 */
public class Interface extends javax.swing.JFrame {

    File arch4 = new File("Administradores.txt");

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();

        this.setLocationRelativeTo(null);
        AccederAdm.setVisible(false);
        Usuario.setVisible(false);
        contraseña.setVisible(false);
        contraseñatextfild.setVisible(false);
        nombretextfild.setVisible(false);

    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/tira-de-pelicula.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PalomitaADm = new javax.swing.JLabel();
        LabelAdministrador = new javax.swing.JLabel();
        SlirBoton = new javax.swing.JButton();
        PalomitaUser = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        this.setVisible(false);
        nombretextfild = new javax.swing.JLabel();
        this.setVisible(false);
        contraseñatextfild = new javax.swing.JLabel();
        contraseña = new javax.swing.JPasswordField();
        AccederAdm = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        JLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PalomitaADm.setBackground(new java.awt.Color(0, 0, 0));
        PalomitaADm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/palomitas-de-maiz (4).png"))); // NOI18N
        PalomitaADm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PalomitaADmMouseClicked(evt);
            }
        });
        PalomitaADm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PalomitaADmKeyPressed(evt);
            }
        });
        getContentPane().add(PalomitaADm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 270, 300));

        LabelAdministrador.setBackground(new java.awt.Color(0, 0, 0));
        LabelAdministrador.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LabelAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        LabelAdministrador.setText("Administrador");
        getContentPane().add(LabelAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 110, 30));

        SlirBoton.setBackground(new java.awt.Color(0, 0, 0));
        SlirBoton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        SlirBoton.setForeground(new java.awt.Color(255, 255, 255));
        SlirBoton.setText("Salir");
        SlirBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlirBotonActionPerformed(evt);
            }
        });
        getContentPane().add(SlirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 90, 30));

        PalomitaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        PalomitaUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PalomitaUserMouseClicked(evt);
            }
        });
        getContentPane().add(PalomitaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 240, 250));

        LabelUsuario.setBackground(new java.awt.Color(0, 0, 0));
        LabelUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelUsuario.setText("Usuario");
        LabelUsuario.setMaximumSize(new java.awt.Dimension(107, 21));
        LabelUsuario.setMinimumSize(new java.awt.Dimension(107, 21));
        getContentPane().add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 70, 20));

        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 150, -1));

        nombretextfild.setBackground(new java.awt.Color(0, 0, 0));
        nombretextfild.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        nombretextfild.setForeground(new java.awt.Color(255, 255, 255));
        nombretextfild.setText("Nombre:");
        getContentPane().add(nombretextfild, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 70, 20));

        contraseñatextfild.setBackground(new java.awt.Color(0, 0, 0));
        contraseñatextfild.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        contraseñatextfild.setForeground(new java.awt.Color(255, 255, 255));
        contraseñatextfild.setText("Contraseña:");
        getContentPane().add(contraseñatextfild, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 100, 20));

        contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 150, -1));

        AccederAdm.setBackground(new java.awt.Color(0, 0, 0));
        AccederAdm.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        AccederAdm.setForeground(new java.awt.Color(255, 255, 255));
        AccederAdm.setText("Acceder");
        AccederAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccederAdmActionPerformed(evt);
            }
        });
        getContentPane().add(AccederAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, -1, -1));

        Titulo.setBackground(new java.awt.Color(0, 0, 0));
        Titulo.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Tu-FILM");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 510, 140));

        jTextField1.setText("Usuario: administrador // contraseña: 1234");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 550, 220, 30));

        JLabelFondo.setBackground(new java.awt.Color(0, 0, 0));
        JLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        JLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cinema-projetor.png"))); // NOI18N
        getContentPane().add(JLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SlirBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SlirBotonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SlirBotonActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed


    }//GEN-LAST:event_UsuarioActionPerformed

    private void contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraseñaActionPerformed

    }//GEN-LAST:event_contraseñaActionPerformed

    private void PalomitaADmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PalomitaADmKeyPressed


    }//GEN-LAST:event_PalomitaADmKeyPressed

    private void PalomitaADmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PalomitaADmMouseClicked

        Usuario.setVisible(true);
        contraseña.setVisible(true);
        contraseñatextfild.setVisible(true);
        nombretextfild.setVisible(true);
        AccederAdm.setVisible(true);

    }//GEN-LAST:event_PalomitaADmMouseClicked

    private void AccederAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccederAdmActionPerformed
        if (!arch4.exists()) {
            try {
                arch4.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try {
            FileReader fr;
            fr = new FileReader(arch4);
            BufferedReader br = new BufferedReader(fr);
            String y;
            int i = 0;
            while ((y = br.readLine()) != null) {
                String v[] = y.split(",");
                if (Usuario.getText().equals(v[0]) && contraseña.getText().equals(v[1])) {
                    Administrador va = new Administrador();
                    va.setVisible(true);
                    this.setVisible(false);
                    i = 1;
                    break;
                }
            }
            if (i == 0) {
                JOptionPane.showMessageDialog(null, "este usuario no existe");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AccederAdmActionPerformed

    private void PalomitaUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PalomitaUserMouseClicked
        new Usuario().setVisible(true);
        this.setVisible(false);
        Metodos mt = new Metodos();

    }//GEN-LAST:event_PalomitaUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccederAdm;
    private javax.swing.JLabel JLabelFondo;
    private javax.swing.JLabel LabelAdministrador;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel PalomitaADm;
    private javax.swing.JLabel PalomitaUser;
    private javax.swing.JButton SlirBoton;
    private javax.swing.JLabel Titulo;
    private javax.swing.JTextField Usuario;
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JLabel contraseñatextfild;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nombretextfild;
    // End of variables declaration//GEN-END:variables
}
